name: Publish stable package to npmjs
on:
  push:
    branches:
      - master
      - bnandwa/4-resolve-issues-with-build
jobs:
  release:
    name: 'Release on NPM'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        name: Setup NodeJs
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        name: Install dependencies
      - name: Setup npmrc file
        run: touch .npmrc && echo ${{ secrets.NPMRC}} > .npmrc
      - run: npx semantic-release
        name: Publish the package on npm
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}